export default Object.freeze({
  COMMUNITY_LIST: 'CommunityList',
  CREATE_POST: 'CreatePost',
  HOME: 'Home',
  LOGIN: 'Login',
  NEARBY_PROFESSIONAL: 'NearbyProfessional',
  NOTIFICATION: 'Notification',
  POST_DETAILS: 'PostDetails',
  SIGNUP: 'Signup',
  WELCOME: 'Welcome',
  USER_PROFILE: 'UserProfile',
  PROFESSIONAL_USER_PROFILE: 'ProfessionalProfile',
  COMMUNITY_DETAILS: 'CommunityDetails',
  TEST: 'Test',
  SCORE: 'Score',
  ADVICE: 'Advice',
  QOUTE: 'Qoute',
  SAVED_POSTS: 'Saved Posts',
  REGULAR_SIGNUP: 'RegularSignup',
});
